version: '3.3'
services:
    bcBuilder:
      image: 'dlbears/bc20:latest'
      container_name: bc_builder
      cap_add: 
        - SYS_ADMIN
      volumes:
        - '$PWD/src:/usr/src/myapp/src'
        - '/tmp/.X11-unix:/tmp/.X11-unix'   
      environment:
        - DISPLAY=unix$DISPLAY #for MacOS, DISPLAY=${HOSTNAME}:0
      devices:
        - /dev/dri
      command: sh -c "
        chown root:root -R ./src
        && chmod -R 777 ./src
        && ./gradlew update
        && ./gradlew build 
        && cd ./client 
        && su derp -c ./battlecode-visualizer"
      