version: '3.3'
services:
    bcBuilder:
      cap_add: 
        - SYS_ADMIN
      volumes:
        - '/tmp/.X11-unix:/tmp/.X11-unix'
        - '$PWD/src:/usr/src/myapp/src'
      container_name: bc_builder
      command: sh -c " 
        cd ./client 
        && su derp -c ./battlecode-visualizer"
      environment:
        - DISPLAY=unix$DISPLAY
      devices:
        - /dev/dri
      image: 'dlbears/bc20:latest'